# Etapa 1: Build
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Copiar csproj y restaurar dependencias
COPY *.csproj ./  
RUN dotnet restore

# Copiar todo el código
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Puerto que usará Render
ENV DOTNET_URLS=http://*:${PORT}
EXPOSE 5000

ENTRYPOINT ["dotnet", "Concesionario.app.dll"]  # Cambia al nombre real de tu dll
